version: '3.9'

services:
  php-apache:    
    build: './build/php'      
    ports:
      - "8081:80"      
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
  mysql:    
    build: './build/mysql'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret  
    volumes:
      - dbData:/var/lib/mysql
volumes:
  app:
  dbData: