controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
load_pizzas:
    path: '/load-pizzas'
    controller: 'App\Controller\PizzaController::loadPizza'